### ISSUE TITLE
请问下，这几类方法可以与Deepspeed Zero一块使用吗？

### ISSUE THREAD

**Issue by YouYouCoding** [feifeibear/long-context-attention#29]
感谢对这些方法的介绍和扩展！ 收获很大。
如题，看了下源码， 都是需要dist的process group参数，不过好像deepspeed没有暴露出这些接口来？ 是不是融合到deepspeed内得需要修改deepspeed源码

**Comment by feifeibear** [comment]
和ZeRO、TP可以兼容的。因为TP兼容时候，num head>TP degree，所以这个repo的attention比Ulysses兼容性更好。
融合起来很简单，就是把全局的sequence parallel process group定义好即可。

参考DeepSpeed tutorial

https://github.com/microsoft/DeepSpeed/blob/42a8eaa705ed30b4a656ac71bdb400772df2cb21/docs/_tutorials/ds-sequence.md?plain=1#L13

```python
def initialize_model_parallel(
    ...
    sequence_parallel_size,
    ...
):
    ...
    num_sequence_parallel_groups: int = world_size // sequence_parallel_size
    num_sequence_data_parallel_groups: int = world_size // sequence_parallel_size // data_parallel_size
    ...
    global _SEQUENCE_PARALLEL_GROUP
    for i in range(num_sequence_parallel_groups):
        ranks = range(i * sequence_parallel_size,
                      (i + 1) * sequence_parallel_size)
        group = torch.distributed.new_group(ranks)
        if rank in ranks:
            _SEQUENCE_PARALLEL_GROUP = group

def get_sequence_parallel_group():
    """Get the sequence parallel group the caller rank belongs to."""
    return _SEQUENCE_PARALLEL_GROUP

```

**Comment by YouYouCoding** [comment]
十分感谢回复，不过好像deepspeed本身并没有暴露出来自定义sequence parallel process group，需要使用Deepspeed-Megatron。
只用deepspeed貌似还不太支持，需要改动比较大：主要是初始化group的时候，
```
group = torch.distributed.new_group(ranks)
```
这里感觉跟zero的默认的group可能会冲突

**Comment by feifeibear** [comment]
> 十分感谢回复，不过好像deepspeed本身并没有暴露出来自定义sequence parallel process group，需要使用Deepspeed-Megatron。 只用deepspeed貌似还不太支持，需要改动比较大：主要是初始化group的时候，
> 
> ```
> group = torch.distributed.new_group(ranks)
> ```
> 
> 这里感觉跟zero的默认的group可能会冲突

不会的，你自己管理好全局的process group分配，让DP、TP、SP、PP的进城组正交。SP进城组再正交分配成ring和ulysses的。
对deepspeed改动不会很大。

**Comment by feifeibear** [comment]
> 十分感谢回复，不过好像deepspeed本身并没有暴露出来自定义sequence parallel process group，需要使用Deepspeed-Megatron。 只用deepspeed貌似还不太支持，需要改动比较大：主要是初始化group的时候，
> 
> ```
> group = torch.distributed.new_group(ranks)
> ```
> 
> 这里感觉跟zero的默认的group可能会冲突

https://github.com/feifeibear/long-context-attention/blob/main/yunchang/globals.py

参考这个文件，在DeepSpeed中定义全局的sequence parallel process group

**Comment by YouYouCoding** [comment]
感谢，我正在适配deepspeed，先试试能否跑通

**Comment by ppengtang** [comment]
Hi @YouYouCoding , 请问你有把这个方法和deepspeed结合起来成功吗？
