### ISSUE TITLE
Comparing Ulysses and Ring with torch profiler

### ISSUE THREAD

**Issue by feifeibear** [feifeibear/long-context-attention#40]
FWD_FLAG="--fwd_only"
NHEADS=8
HEAD_SIZE=128
GROUP_NUM=1
BS=2
ulysses degree=8

- SEQLEN=16384

<img width="933" alt="image" src="https://github.com/feifeibear/long-context-attention/assets/5706969/3c52c7f6-c7a0-4b02-b4f3-35cff44dec4d">

- SEQLEN=8192

<img width="518" alt="image" src="https://github.com/feifeibear/long-context-attention/assets/5706969/5c7fee58-6014-4d1a-8694-62d9c87150a3">

**Conclusion:**
Long Context, Less Comm/Computation Ratio. Because computation is O(N^2), while communication is O(N).

- Ulysses Degree=8

<img width="1081" alt="image" src="https://github.com/feifeibear/long-context-attention/assets/5706969/55d4bf41-628e-4232-950b-bfa1a0cf7654">

- Ring Degree=8

<img width="1277" alt="image" src="https://github.com/feifeibear/long-context-attention/assets/5706969/aae55918-705d-48d1-bbec-555b16061c08">

**Conclusion:**
Ulysses is more efficient in Communication and Computation, as you can see in four iterations ring-attn elapse is over 100ms, while Ulysses is about 60ms.

**Comment by nullnonenilNULL** [comment]
结合上面分析和 benchmark 数据，这里怎么理解单用 ulysses 比混用 ulysses 和 ring 性能差？原因是单用 ulysses 做完 alltoall，会把 h 切的比较小，影响了 gemm 计算的密度？

**Comment by feifeibear** [comment]
> 结合上面分析和 benchmark 数据，这里怎么理解单用 ulysses 比混用 ulysses 和 ring 性能差？原因是单用 ulysses 做完 alltoall，会把 h 切的比较小，影响了 gemm 计算的密度？

你没正确理解这个图。它想说单机八卡nvlink环境，ulysses比ring整体性能好很多。因为ring把完整attention计算切分了，导致整体计算时间变长。Ulysess增加额外all2all但是时间比例很小。二者比较下来ring就有劣势。

混用肯定不会比ring和ulysses差。

**Comment by nullnonenilNULL** [comment]
> > 结合上面分析和 benchmark 数据，这里怎么理解单用 ulysses 比混用 ulysses 和 ring 性能差？原因是单用 ulysses 做完 alltoall，会把 h 切的比较小，影响了 gemm 计算的密度？
> 
> 你没正确理解这个图。它想说单机八卡nvlink环境，Ring-Attention性能不如Ulysses。 ulysses比ring整体性能好很多。因为ring把完整attention计算切分了，导致整体计算时间变长。Ulysess增加额外all2all但是时间比例很小。二者比较下来ring就有劣势。
嗯嗯，感谢你的工作和回复。图里表达的逻辑，我没有疑问哈；
![image](https://github.com/feifeibear/long-context-attention/assets/34435196/b337971f-b799-4a89-b8ea-889eda27250e)
结合您这里的分析和 readme中的吞吐数据，我主要是在理解，假设 ulysses 切分不受限情况下，为什么单用 ulysses 比混用两种方案性能低，为什么不是 ulysses 性能最优；

**Comment by nullnonenilNULL** [comment]
> > 结合上面分析和 benchmark 数据，这里怎么理解单用 ulysses 比混用 ulysses 和 ring 性能差？原因是单用 ulysses 做完 alltoall，会把 h 切的比较小，影响了 gemm 计算的密度？
> 
> 你没正确理解这个图。它想说单机八卡nvlink环境，Ring-Attention性能不如Ulysses。 ulysses比ring整体性能好很多。因为ring把完整attention计算切分了，导致整体计算时间变长。Ulysess增加额外all2all但是时间比例很小。二者比较下来ring就有劣势。

嗯嗯，感谢你的工作和回复。图里表达的逻辑，我没有疑问哈；
![image](https://github.com/feifeibear/long-context-attention/assets/34435196/2df44abd-770a-4fef-8282-877d0a5b3d8f)

结合您这里的分析和 readme中的吞吐数据，我主要是在理解，假设 ulysses 切分不受限情况下，为什么单用 ulysses 比混用两种方案性能低，为什么不是 ulysses 性能最优；

**Comment by feifeibear** [comment]
> > > 结合上面分析和 benchmark 数据，这里怎么理解单用 ulysses 比混用 ulysses 和 ring 性能差？原因是单用 ulysses 做完 alltoall，会把 h 切的比较小，影响了 gemm 计算的密度？
> > 
> > 
> > 你没正确理解这个图。它想说单机八卡nvlink环境，Ring-Attention性能不如Ulysses。 ulysses比ring整体性能好很多。因为ring把完整attention计算切分了，导致整体计算时间变长。Ulysess增加额外all2all但是时间比例很小。二者比较下来ring就有劣势。
> 
> 嗯嗯，感谢你的工作和回复。图里表达的逻辑，我没有疑问哈； ![image](https://private-user-images.githubusercontent.com/34435196/324325362-2df44abd-770a-4fef-8282-877d0a5b3d8f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYwODg2NjIsIm5iZiI6MTcxNjA4ODM2MiwicGF0aCI6Ii8zNDQzNTE5Ni8zMjQzMjUzNjItMmRmNDRhYmQtNzcwYS00ZmVmLTgyODItODc3ZDBhNWIzZDhmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE5VDAzMTI0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE4ZmFjMDMyODAzNmY3ZTAzNzk3MzRhNzJiNTZmZWM2NmM0N2JkYzgyNDk2MjExZTBjZWZjMjE1YTk0YmMwN2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Kgrxu-Rgkb3WCubQsDAGF0DoRTR42yc8SvV9jRPC9P4)
> 
> 结合您这里的分析和 readme中的吞吐数据，我主要是在理解，假设 ulysses 切分不受限情况下，为什么单用 ulysses 比混用两种方案性能低，为什么不是 ulysses 性能最优；

ulysses在nvlink单个节点通常最有。因为nvlink是同构网络，点对点带宽都一样。如果换成异构网络，比如pcie或者多机多卡，ulysses就不是最优了。详细数据见readme里的技术报告链接。
