### ISSUE TITLE
显存占用问题

### ISSUE THREAD

**Issue by realgump** [feifeibear/long-context-attention#56]
<img width="883" alt="image" src="https://github.com/feifeibear/long-context-attention/assets/37771769/1fa490ff-1931-4f9f-9d15-04e18f85e242">
您好，论文表里面的zero-1和dp的激活值为什么是A/N呢？如果是这样的话，sp+zero-1相比zero-1似乎没有优势。

**Comment by feifeibear** [comment]
zero-dp没有通信activation，只通信了weight和grad。
