### ISSUE TITLE
What does mean the figure 5?

### ISSUE THREAD

**Issue by takfate** [feifeibear/long-context-attention#68]
<img width="993" alt="image" src="https://github.com/user-attachments/assets/f65e8826-4b45-497d-b827-bf09a5c0e4a8">
请问这个图具体是什么设定？
总batch是8个样本。
我的理解是对于DP，8个样本分别在每个gpu上。
对于SP，8个样本拼成了1个长序列，让8个gpu用SP共同forward这个序列，
我的理解对吗

**Comment by feifeibear** [comment]
是的，gbs=8，序列长度4K。我们可以用DP，沿着gbs维度切分，也可以用SP沿着序列维度切分。这个图在比较这两种切分的优劣。

**Comment by feifeibear** [comment]
参考论文中那张通信分析的Table。SP就是比DP通信量更多。
