### ISSUE TITLE
在并行度相同的情况下，USP和ulysess、ring-sp性能相比如何呢？

### ISSUE THREAD

**Issue by hb-jw** [feifeibear/long-context-attention#73]
你好，感谢你的工作，很棒！我想请教一下，在并行度相同的情况下，USP和ulysess、ring-sp性能相比如何呢？我在技术报告中似乎没有看到相关的分析，因此想请教一下。比如并行度总数为8，那么2×4的USP和并行度为8的ulysess、ring-sp性能相比如何呢？

**Comment by feifeibear** [comment]
USP的表现和你的运行它的硬件有关。主页展示了L20数据的数据，你可以看到ulysses=4, ring=2性能最好。这是因为它的网络拓扑就是类似2x4的网格（PCIe-switch+QPI）

https://arxiv.org/abs/2405.07719
