### ISSUE TITLE
Megatro-LM适配代码

### ISSUE THREAD

**Issue by 233function** [feifeibear/long-context-attention#85]
你好👋我目前在做长文本的相关研究，想要咨询下yunchang有没有可以适配Megatron-LM的代码？

**Comment by feifeibear** [comment]
> 你好👋我目前在做长文本的相关研究，想要咨询下yunchang有没有可以适配Megatron-LM的代码？

https://github.com/FlagOpen/FlagScale/commit/f98ee1e293bd906cc77f512f7a884b2030c10a12

很多人已经把USP弄到megatron-LM里了
