### ISSUE TITLE
支持样本间隔离吗

### ISSUE THREAD

**Issue by Lzhang-hub** [feifeibear/long-context-attention#86]
对于一条数据中存在多样本的情况，我理解Ulysses all-to-all的形式可以支持[without cross attention](https://github.com/MeetKai/functionary/tree/main/functionary/train/packing)，请教一下加入ring-attention之后，还支持吗？

**Comment by feifeibear** [comment]
你传给ring flash attention一个mask可以么？

**Comment by Lzhang-hub** [comment]
我看了一下ring flash attention的实现，目前版本应该是不支持。

我理解现在attention计算都是采用的FA 的varlen函数，它的attention mask是依赖cu_seqlens_q和cu_seqlens_k配置的，[代码中](https://github.com/feifeibear/long-context-attention/blob/81607c81dd9d4eefac54d9045fcf20484db1b4f3/yunchang/ring/ring_flash_attn_varlen.py#L51)设置的cu_seqlens_q和cu_seqlens_k是同一个值，对变长文本应该是做不到样本间隔离。

zhuzilin的[实现](https://github.com/zhuzilin/ring-flash-attention/blob/main/ring_flash_attn/llama3_flash_attn_varlen.py)似乎是支持了这种without cross attention，我研究研究两个结合一下。
