### ISSUE TITLE
USP vs UP性能不及预期

### ISSUE THREAD

**Issue by Tengxu-Sun** [feifeibear/long-context-attention#88]
@feifeibear 大佬你好，基于仓库中的test 脚本对[USP](https://github.com/feifeibear/long-context-attention/blob/main/test/test_hybrid_attn.py) 和 [UP](https://github.com/feifeibear/long-context-attention/blob/main/test/test_ulysses_attn.py)性能做了个benchmark对比，实验设置和结果如下表所示

* USP设置：up2+ring atten 2
* UP设置：up4

| index | device | batch_size | seqlen |  heads | d | USP time cost(ms) | Ulysses time cost(ms) |
|-----|-----|-----|-----|-----|-----|-----|-----|
| 1 | 4090 pcie | 40 | 1024 | 40 | 128 | 75.70 | 55.57 |
| 2 | 4090 pcie | 40 | 3600 | 40 | 128 | 248.63 |  175.41 |
| 3 | 4090 pcie | 1 | 10240 | 40 | 128 | 15.79 | 12.69 |
| 4 | 4090pcie  | 1 | 36000 | 40 | 128 | 84.76 | 72.72 |
| 5 | h800 NVL  | 40 | 1024 | 40 | 128 | 3.39 | 2.68 |
| 6 | h800 NVL | 40 | 3600 | 40 | 128 | 23.69 | 26.67 |

以上测试条件下，USP都不及Ulysses的性能，这与仓库这里的结论 https://github.com/feifeibear/long-context-attention/blob/main/README.md#best-practice-for-4d-parallelism 第一点不相符吧，请问这是为啥呢

**Comment by feifeibear** [comment]
不同机器表现不一样，你测的case在你的的机器都是Ulysses最好。你把ulysses=1，USP就是ulysses了。Ulysses和Ring只是USP两个特殊情况，使用时用USP搜一下最佳的ulysses_degree和ring_degree配置。
